name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        deno: [canary]
        os: [ubuntu-latest]

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Set-up
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: ${{ matrix.deno }}

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --unstable --coverage=cov --allow-read

      - name: Coverage
        run: deno coverage cov

      - name: Remove Coverage
        shell: bash
        run: |
          rm -rf cov
