name: year_2017

on:
  push:
    paths:
      - "year_2017/**"
  pull_request:
    paths:
      - "year_2017/**"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Set-up
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: canary

      - name: Format
        run: deno fmt --check year_2017

      - name: Lint
        run: deno lint year_2017

      - name: Test
        run: deno test --allow-read year_2017
